const data = [
  {
    id: "105",
    link: "https://knowverse.idare.ai/",
    imageUrl: "./images/project-pro/knowverse.webp",
    name: "KnowVerse AI (AI-powered chatbot application)",
    tools: ["Reactjs", "Tailwindcss", "shadcdn"],
  },
  {
    id: "104",
    link: "https://aieasy.idare.ai/easy",
    imageUrl: "./images/project-pro/aieasy.webp",
    name: "AI Easy (AI platform for data processing, machine learning)",
    tools: ["Reactjs", "Tailwindcss", "shadcdn"],
  },
  {
    id: "102",
    link: "https://idare.ai/",
    imageUrl: "./images/project-pro/website.webp",
    name: "Knowverse Website",
    tools: ["Nextjs", "Tailwindcss", "shadcdn"],
  },
  {
    id: "103",
    link: "https://www.movement.idare.ai/",
    imageUrl: "./images/project-pro/dashboard.webp",
    name: "Dashboard",
    tools: ["Reactjs", "Plotlyjs", "Redux", "Material UI"],
  },
  {
    id: "1",
    link: "https://myunisearch.com",
    imageUrl: "./images/project-pro/unisearch.webp",
    name: "UniSearch (Study Abroad Portal)",
    tools: ["Nextjs", "Material UI", "Nestjs", "Redux", "tailwindcss"],
  },
  {
    id: "11",
    link: "https://studyinternational.net.au",
    imageUrl: "./images/project-pro/studyinternational.webp",
    name: "Study International (Study Abroad Portal)",
    tools: ["Nextjs", "Ant Design", "Nestjs", "Redux", "tailwindcss"],
  },
  {
    id: "12",
    link: "https://24onbd.com",
    imageUrl: "./images/project-pro/onbd24.webp",
    name: "24onbd (News Aggregator Site)",
    tools: ["Nextjs", "Ant Design", "Nestjs", "Redux", "tailwindcss"],
  },
  {
    id: "13",
    link: "https://m4yours.com",
    imageUrl: "./images/project-pro/m4yours.webp",
    name: "m4yours (Portfolio Website)",
    tools: ["Nextjs", "Ant Design", "Nestjs", "Redux", "tailwindcss"],
  },
  {
    id: "6",
    link: "https://boostontime.com/ebay-template-builder",
    imageUrl: "./images/project-pro/boostontime.webp",
    name: "Boostontime (Ebay Template Builder)",
    tools: ["HTML", "CSS", "Bootstrap", "PHP", "jQuery"],
  },
  {
    id: "7",
    link: "https://boostontime.com/amazon-data-extractor",
    imageUrl: "./images/project-pro/amazon-data-crawler.webp",
    name: "Amazon Data Crawler (Data Crawler)",
    tools: ["HTML", "CSS", "Bootstrap", "PHP", "jQuery"],
  },
  {
    id: "8",
    link: "https://rihla.io",
    imageUrl: "./images/project-pro/rihla.webp",
    name: "Rihla International School (School)",
    tools: ["HTML", "CSS", "Bootstrap", "Laravel", "jQuery"],
  },
  {
    id: "9",
    link: "https://www.mqrsbrands.com/",
    imageUrl: "./images/project-pro/mqrsbrands.webp",
    name: "MQRS Brands (Shopify Store)",
    tools: ["HTML", "CSS", "Liquid", "jQuery"],
  },

  // {
  //   id: "10",
  //   link: "https://eurowheelusa.com/",
  //   imageUrl: "./images/project-pro/eurowheelusa.webp",
  //   name: "Eurowheelusa (Shopify Store)",
  //   tools: ["HTML", "CSS", "Liquid", "jQuery"],
  // },
];

export default data;
