const data = [
  {
    id: "per1",
    link: "http://makeshift-whistle.surge.sh/",
    imageUrl: "./images/project-per/nature.webp",
    gitHub: "https://github.com/mizankhangit/natours",
    name: "Nature (Tour booking website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: "per2",
    link: "http://silent-burst.surge.sh/",
    imageUrl: "./images/project-per/trillo.webp",
    gitHub: "https://github.com/mizankhangit/trillo",
    name: "Trillo (Hotel booking website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: "per3",
    link: "http://melted-pet.surge.sh/",
    imageUrl: "./images/project-per/nexter.webp",
    gitHub: "https://github.com/mizankhangit/nexter",
    name: "Nexter (Real Estate website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: "per4",
    link: "http://vengeful-goldfish.surge.sh/",
    imageUrl: "./images/project-per/omnifood.webp",
    gitHub: "https://github.com/mizankhangit/omnifood",
    name: "Omnifood (Restaurent website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: "per5",
    link: "https://modern-responsive-web.netlify.app/",
    imageUrl: "./images/project-per/modern-web.webp",
    gitHub: "https://github.com/mizankhangit/modern-responsive-web",
    name: "Modern web",
    tools: ["HTML", "CSS", "jQuery"],
    tag: "hc",
  },
  {
    id: "per6",
    link: "https://apple-replica-app.netlify.app/",
    imageUrl: "./images/project-per/apple.webp",
    gitHub: "https://github.com/mizankhangit/apple-replica",
    name: "Apple replica clone",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: "per7",
    link: "https://advanced-dom.vercel.app/",
    imageUrl: "./images/project-per/dom.webp",
    gitHub: "https://github.com/mizankhangit/advanced-dom",
    name: "Advanced DOM manipulation",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: "per8",
    link: "https://mapty.vercel.app/",
    imageUrl: "./images/project-per/mapty.webp",
    gitHub: "https://github.com/mizankhangit/mapty",
    name: "Mapty",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: "per9",
    link: "https://form-validation-js.vercel.app/",
    imageUrl: "./images/project-per/form.webp",
    gitHub: "https://github.com/mizankhangit/form-validation-js",
    name: "Simple form validation",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: "per10",
    link: "https://rock-paper-scissors-first-game.netlify.app/",
    imageUrl: "./images/project-per/rock.webp",
    gitHub: "https://github.com/mizankhangit/rock-paper-scissors-game-",
    name: "Rock-paper-scissors game",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: "per11",
    link: "https://mycomplex-app.herokuapp.com/",
    imageUrl: "./images/project-per/complexapp.webp",
    gitHub: "https://github.com/mizankhangit/complexapp",
    name: "Simple blogging app",
    tools: ["HTML", "Bootstrap", "Node.js", "MongoDB"],
    tag: "no",
  },
  {
    id: "per11",
    link: "https://gatsby-restaurant-project-first.netlify.app/",
    imageUrl: "./images/project-per/restaurant.webp",
    gitHub: "https://github.com/mizankhangit/gatsby-restaurant",
    name: "Restaurant website",
    tools: ["HTML", "CSS", "Gatsby"],
    tag: "re",
  },
  {
    id: "per12",
    link: "https://breaking-bad-cast.netlify.app/",
    imageUrl: "./images/project-per/breaking.webp",
    gitHub: "https://github.com/mizankhangit/breaking-bad-cast",
    name: "Character search app",
    tools: ["HTML", "CSS", "React"],
    tag: "re",
  },
  {
    id: "per13",
    link: "https://mcity-b672b.firebaseapp.com/",
    imageUrl: "./images/project-per/mcity.webp",
    gitHub: "https://github.com/mizankhangit/mcity",
    name: "Football team MCity",
    tools: ["HTML", "CSS", "React"],
    tag: "re",
  },
  {
    id: "per14",
    link: "https://venue-react-app.netlify.app/",
    imageUrl: "./images/project-per/venue.webp",
    gitHub: "https://github.com/mizankhangit/venue",
    name: "The venue musical events",
    tools: ["HTML", "CSS", "React"],
    tag: "re",
  },
  {
    id: "per15",
    link: "https://password-generator-vert.vercel.app/",
    imageUrl: "./images/project-per/password.webp",
    gitHub: "https://github.com/mizankhangit/password-generator",
    name: "Password generator",
    tools: ["HTML", "CSS", "Angular"],
    tag: "an",
  },
  {
    id: "per16",
    link: "http://moldy-trousers.surge.sh/",
    imageUrl: "./images/project-per/clock.webp",
    gitHub: "https://github.com/mizankhangit/analog-clock",
    name: "Analog clock",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: "per17",
    link: "https://simpletodoapp1.herokuapp.com/",
    imageUrl: "./images/project-per/todo.webp",
    gitHub: "https://github.com/mizankhangit/todo-app",
    name: "Simple to do app",
    tools: ["HTML", "Bootstrap", "Node.js", "MonogDB"],
    tag: "no",
  },
];

export default data;
