const data = [
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://pig-game-seven.vercel.app/",
    imageUrl: "./images/project-per/pig-game.webp",
    gitHub: "https://github.com/mizankhangit/pig-game",
    name: "Pig Game",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://speech-text-reader-eight.vercel.app/",
    imageUrl: "./images/project-per/speech-text-reader.webp",
    gitHub: "https://github.com/mizankhangit/speech-text-reader",
    name: "Speech Text Reader",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://custom-modal.vercel.app/",
    imageUrl: "./images/project-per/custom-modal.webp",
    gitHub: "https://github.com/mizankhangit/custom-modal",
    name: "Custom Modal",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://guess-number-game-weld.vercel.app/",
    imageUrl: "./images/project-per/guess-number-game.webp",
    gitHub: "https://github.com/mizankhangit/guess-number-game",
    name: "Guess Number Game",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://light-dark-theme-liard.vercel.app/",
    imageUrl: "./images/project-per/light-dark-theme.webp",
    gitHub: "https://github.com/mizankhangit/light-dark-theme",
    name: "Light Dark Theme",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://countdown-timer-ecru.vercel.app/",
    imageUrl: "./images/project-per/custom-countdown.webp",
    gitHub: "https://github.com/mizankhangit/countdown-timer",
    name: "Custom Countdown",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://bookmark-app-six.vercel.app/",
    imageUrl: "./images/project-per/bookmark-app.webp",
    gitHub: "https://github.com/mizankhangit/bookmark-app",
    name: "Bookmark App",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://pizza-delivery-appp.herokuapp.com/",
    imageUrl: "./images/project-per/pizza.webp",
    gitHub: "https://github.com/mizankhangit/pizza-delivery-app",
    name: "Pizza delivery app",
    tools: ["React", "Bootstrap", "Node.js", "MongoDB"],
    tag: "no",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "http://makeshift-whistle.surge.sh/",
    imageUrl: "./images/project-per/nature.webp",
    gitHub: "https://github.com/mizankhangit/natours",
    name: "Nature (Tour booking website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "http://silent-burst.surge.sh/",
    imageUrl: "./images/project-per/trillo.webp",
    gitHub: "https://github.com/mizankhangit/trillo",
    name: "Trillo (Hotel booking website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "http://melted-pet.surge.sh/",
    imageUrl: "./images/project-per/nexter.webp",
    gitHub: "https://github.com/mizankhangit/nexter",
    name: "Nexter (Real Estate website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "http://vengeful-goldfish.surge.sh/",
    imageUrl: "./images/project-per/omnifood.webp",
    gitHub: "https://github.com/mizankhangit/omnifood",
    name: "Omnifood (Restaurent website)",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://modern-responsive-web.netlify.app/",
    imageUrl: "./images/project-per/modern-web.webp",
    gitHub: "https://github.com/mizankhangit/modern-responsive-web",
    name: "Modern web",
    tools: ["HTML", "CSS", "jQuery"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://apple-replica-app.netlify.app/",
    imageUrl: "./images/project-per/apple.webp",
    gitHub: "https://github.com/mizankhangit/apple-replica",
    name: "Apple replica clone",
    tools: ["HTML", "CSS"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://advanced-dom.vercel.app/",
    imageUrl: "./images/project-per/dom.webp",
    gitHub: "https://github.com/mizankhangit/advanced-dom",
    name: "Advanced DOM manipulation",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://mapty.vercel.app/",
    imageUrl: "./images/project-per/mapty.webp",
    gitHub: "https://github.com/mizankhangit/mapty",
    name: "Mapty",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://form-validation-js.vercel.app/",
    imageUrl: "./images/project-per/form.webp",
    gitHub: "https://github.com/mizankhangit/form-validation-js",
    name: "Simple form validation",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://rock-paper-scissors-first-game.netlify.app/",
    imageUrl: "./images/project-per/rock.webp",
    gitHub: "https://github.com/mizankhangit/rock-paper-scissors-game-",
    name: "Rock-paper-scissors game",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://reactcomplexapp.vercel.app/",
    imageUrl: "./images/project-per/complexapp.webp",
    gitHub: "https://github.com/mizankhangit/reactcomplexapp",
    name: "Simple blogging app",
    tools: ["React", "Bootstrap", "Node.js", "MongoDB"],
    tag: "no",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://gatsby-restaurant-project-first.netlify.app/",
    imageUrl: "./images/project-per/restaurant.webp",
    gitHub: "https://github.com/mizankhangit/gatsby-restaurant",
    name: "Restaurant website",
    tools: ["HTML", "CSS", "Gatsby"],
    tag: "re",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://breaking-bad-cast.netlify.app/",
    imageUrl: "./images/project-per/breaking.webp",
    gitHub: "https://github.com/mizankhangit/breaking-bad-cast",
    name: "Character search app",
    tools: ["HTML", "CSS", "React"],
    tag: "re",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://mcity-b672b.firebaseapp.com/",
    imageUrl: "./images/project-per/mcity.webp",
    gitHub: "https://github.com/mizankhangit/mcity",
    name: "Football team MCity",
    tools: ["HTML", "CSS", "React"],
    tag: "re",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://venue-react-app.netlify.app/",
    imageUrl: "./images/project-per/venue.webp",
    gitHub: "https://github.com/mizankhangit/venue",
    name: "The venue musical events",
    tools: ["HTML", "CSS", "React"],
    tag: "re",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://password-generator-vert.vercel.app/",
    imageUrl: "./images/project-per/password.webp",
    gitHub: "https://github.com/mizankhangit/password-generator",
    name: "Password generator",
    tools: ["HTML", "CSS", "Angular"],
    tag: "an",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "http://moldy-trousers.surge.sh/",
    imageUrl: "./images/project-per/clock.webp",
    gitHub: "https://github.com/mizankhangit/analog-clock",
    name: "Analog clock",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "js",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://simpletodoapp1.herokuapp.com/",
    imageUrl: "./images/project-per/todo.webp",
    gitHub: "https://github.com/mizankhangit/todo-app",
    name: "Simple to do app",
    tools: ["HTML", "Bootstrap", "Node.js", "MonogDB"],
    tag: "no",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://splash-page-mu.vercel.app/",
    imageUrl: "./images/project-per/splash.webp",
    gitHub: "https://github.com/mizankhangit/splash-page",
    name: "Splash Page",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://animated-template-sigma.vercel.app/",
    imageUrl: "./images/project-per/animated-template.webp",
    gitHub: "https://github.com/mizankhangit/animated-template",
    name: "Animated Template",
    tools: ["HTML", "CSS", "JavaScript"],
    tag: "hc",
  },
  {
    id: (Date.now() + Math.random()) * 10000,
    link: "https://react-todo-beta-eight.vercel.app/",
    imageUrl: "./images/project-per/react-todo.webp",
    gitHub: "https://github.com/mizankhangit/react-todo",
    name: "React todo app",
    tools: ["HTML", "CSS", "react"],
    tag: "re",
  },
];

export default data;
